version: "3"
services:
    zhongkui-waf:
        image: dosoc/zhongkui-waf-alpine:20240819
        container_name: zhongkui-waf
        restart: unless-stopped
        environment:
            #- GEOIP_LICENSE_KEY=you key
            #- GEOIP_ACCOUNT_ID=you id
            - MYSQL_HOST=127.0.0.1
            - MYSQL_USER=root
            - MYSQL_PASSWORD=6CsIaDsfRike
        volumes:
            - ./zhongkui-waf:/usr/local/openresty/zhongkui-waf
            - ./GeoIP:/usr/local/share/GeoIP
        network_mode: host
        depends_on:
            - zhongkui-mysql
        
    zhongkui-mysql:
        image: mysql:8.0.37
        container_name: zhongkui-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: zhongkui_waf
            MYSQL_ROOT_PASSWORD: 6CsIaDsfRike
        volumes:
            - ./mysql:/var/lib/mysql
            - ./log:/var/log/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        network_mode: host
        #ports:
        #    - 3306:3306