version: "3"
services:
    zhongkui-waf:
        image: dosoc/zhongkui-waf-alpine:20240819
        container_name: zhongkui-waf
        restart: unless-stopped
        ports:
            - 1226:1226
            - 80:80
            - 443:443
        environment:
            #- GEOIP_LICENSE_KEY=you key
            #- GEOIP_ACCOUNT_ID=you id
            - MYSQL_HOST=zhongkui-mysql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=6CsIaDsfRike
        volumes:
            - ./zhongkui-waf:/usr/local/openresty/zhongkui-waf
            - ./GeoIP:/usr/local/share/GeoIP
        networks:
            - zkwaf-net
        depends_on:
            - zhongkui-mysql
        
    zhongkui-mysql:
        image: mysql:5.7.44
        # image: mysql:8.0.37
        container_name: zhongkui-mysql
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: zhongkui_waf
            MYSQL_ROOT_PASSWORD: 6CsIaDsfRike
        volumes:
            - ./mysql:/var/lib/mysql
            - ./log:/var/log/mysql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - zkwaf-net
networks:
  zkwaf-net:
    driver: bridge